// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:385344616624:web:a2a307ac36ded8d4c02375',
    messagingSenderId: '385344616624',
    projectId: 'authentication-a0a98',
    authDomain: 'authentication-a0a98.firebaseapp.com',
    storageBucket: 'authentication-a0a98.appspot.com',
    measurementId: 'G-JELJ55H5BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:385344616624:android:be93fc3def52429ec02375',
    messagingSenderId: '385344616624',
    projectId: 'authentication-a0a98',
    storageBucket: 'authentication-a0a98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:385344616624:ios:d078bc093b2dd5ebc02375',
    messagingSenderId: '385344616624',
    projectId: 'authentication-a0a98',
    storageBucket: 'authentication-a0a98.appspot.com',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:385344616624:ios:d078bc093b2dd5ebc02375',
    messagingSenderId: '385344616624',
    projectId: 'authentication-a0a98',
    storageBucket: 'authentication-a0a98.appspot.com',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:385344616624:web:db111222147447fdc02375',
    messagingSenderId: '385344616624',
    projectId: 'authentication-a0a98',
    authDomain: 'authentication-a0a98.firebaseapp.com',
    storageBucket: 'authentication-a0a98.appspot.com',
    measurementId: 'G-EKHPHVQ3KP',
  );
}
